name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

     runs-on: ubuntu-24.04


    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install C++ compiler
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Compile C++ program
      run: g++ -o program src/main.cpp


    - name: Run the C++ program
      run: ./program
